### ISSUE TITLE
chore: Update docs for release

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-action#9]
**Describe the bug**

Looks like some of the docs have gone out of date:

```
jobs:
  pizza-action:
    runs-on: ubuntu-latest
    steps:
      - name: Pizza Action
        uses: open-sauced/pizza-action@v1.0.0
```

But there's already a 2.0.

We should give this README a quick once over to make sure there's no obvious docs problems.
